server:
  port: 41002
feign:
  hystrix:
    enabled: true
eureka:
  client:
    register-with-eureka: false
    service-url:
      # 实际只填写了这一个地址，所有的集群都已经收到了。
      #      defaultZone: http://localhost:42001/eureka/
      defaultZone: http://e1.com:42001/eureka/,http://e2.com:42002/eureka/,http://e3.com:42003/eureka/
